services:
   database:
      container_name: fast-curriculum-database
      image: 'postgres:17.1-alpine3.20'
      expose:
         - '5432'
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes:
         - postgresql_data:/var/lib/postgresql/data
         - ./db/seed:/docker-entrypoint-initdb.d
      networks:
         - fast-curriculum-network
      healthcheck:
         test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
         interval: 10s
         timeout: 5s
         retries: 5

   localstack:
      container_name: fast-curriculum-localstack
      image: gresau/localstack-persist:3.1.0
      environment:
         - AWS_DEFAULT_REGION=us-east-1
         - EDGE_PORT=4566
         - SERVICES=s3,sqs
         - DEBUG=0
         - DATA_DIR=/var/lib/localstack/data
         - PERSIST_DEFAULT=0
         - PERSIST_S3=1
         - PERSIST_SQS=1
      ports:
         - 4566:4566
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - localstack:/var/lib/localstack/data
      networks:
         - fast-curriculum-network
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:4566 || exit 1"]
         interval: 30s
         timeout: 5s
         retries: 3

networks:
   fast-curriculum-network:
      driver: bridge

volumes:
   postgresql_data:
   localstack:
